language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - 8
  - 10
  - 12
  - 13
  - node
before_deploy: npm run prepublishOnly
deploy:
  provider: npm
  email: andreas@stassi.net
  api_token:
    secure: biuFB1b3jEw+W3y8kdPNfENrY3C5PkpsV/5zNcrDCTpVKx7+aGbAr7e6X2IZ9lH4CAE04PWmtogSEYwlDtk+DjriIAynOQbB4JHqlyOMfjVVw0stXM/QlEjALE1+OgrhK4vQcs8DQgjimnBi0WkdMkCr1c7NKMbZ7nFVB7MOzzgeZmQyW7YrxMCwC7zmQMi6nNtoFIuRMT2B1FqHwdEtxDVt9nW0QkLXsoHPJ5JRoeAbEytVbLvoCSU0ZG7fyIO2B2YCdjxZUTZlPplZ0VlZJrMopwSY5IAFCVhBD5wlRDc43LTxj6jdY5vMtX2IoYUlA5spBWqs0BYc8k7iAgYueDlRrNekVDo8z38g0mpq15yJneSi2nZr2nKnQIVxTYpWu4j6VONEKnpnTWQe9eCuAK/ql1WiZKPyd18+mRxCBi2nhKzx1nIEdrp3phAt51dUT7kZHlVsK86R1E0HbPlsHWa6g/fPiPMBaKzjOj6yRZRLgkCRqctxrEjrSdZ4K6WrVZhXYHRZHOpU4VNwgadc/s0Ag5gDIghn3GSswgHyNKB5vSHjWOTRQsRjExSvZ6c+e+KqaaxdvhoeXqnq8cY/InpzarlCWaS5qvG6LTLNAUVfyf/qGEfuVqS15nfSf/q2R0NagwYV2u/aKxGeYul49OiGMBTmmBanym3CiWSCHvw=
  edge: true
  on:
    condition: $TRAVIS_OS_NAME = linux
    node_js: 13
